spring:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/poc_db_one
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
db2:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/poc_db_two
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
csl:
  properties:
    trwWindowInSeconds: 10
    trwMinNoOfCalls: 5
    fmtErrTRWWindowInSeconds: 10
    fmtErrTRWMinNoOfCalls: 3
#resilience4j.circuitbreaker.instances.csl.registerHealthIndicator
#  resilience4j.circuitbreaker.instances.csl.slidingWindowSize=5
#  resilience4j.circuitbreaker.instances.csl.slidingWindowType=COUNT_BASED
#  resilience4j.circuitbreaker.instances.csl.minimumNumberOfCalls=5
#  resilience4j.circuitbreaker.instances.csl.waitDurationInOpenState=10000
#  resilience4j.circuitbreaker.instances.csl.permittedNumberOfCallsInHalfOpenState=3
#  resilience4j.circuitbreaker.instances.csl.failureRateThreshold=50
#resilience4j:
#  timelimiter:
#    instances:
#      csl:
#        timeoutDuration: 2s
#        cancelRunningFuture: true


#resilience4j.circuitbreaker:
#  configs:
#    default:
#      registerHealthIndicator: true
#      slidingWindowSize: 50
#
#resilience4j.timelimiter:
#  configs:
#    default:
#      timeoutDuration: 5s
#      cancelRunningFuture: true